language: node_js
node_js:
  - "lts/*"

sudo: false

cache:
  directories:
    - node_modules

install:
  - npm install -g yarn

script:
  - cd misc
  - yarn
  - yarn start

branches:
  only:
    - crontab-update
